### ISSUE TITLE
What's the license on the models?

### ISSUE THREAD

**Issue by vorg** [sbtron/BabylonJS-glTFLoader#1]
I would love to use them to test my gltf parser https://github.com/pex-gl/pex-gltf

**Comment by xeolabs** [comment]
Ditto!

**Comment by sbtron** [comment]
Sorry I seem to have missed this. These were meant to be a test bed to try out the pbr extensions etc with the goal of submitting them all to the https://github.com/KhronosGroup/glTF-Sample-Models repo once the feature / extension is integrated into glTF spec.
Please feel free to use the models to test things out with the caveat that these may continue to evolve with the spec. 
I have updated the readme with this explanation. Please let me know if you would like something more explicit.
