### ISSUE TITLE
Normals got flipped

### ISSUE THREAD

**Issue by emackey** [sbtron/BabylonJS-glTFLoader#10]
Hi guys,

An update to BabylonJS was recently pushed to this repo (in 6a74f09e07), and the direction of the Y-axis on the normal maps has flipped during that update.  If I load the [NormalTangentTest](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/NormalTangentTest) object with the latest version of this repo, I get mixed-up normal maps, like this:

![babylonjs_bad](https://cloud.githubusercontent.com/assets/1235080/26522772/1728d566-42d6-11e7-84f1-7fdb16755603.png)

Prior to the update to BabylonJS, the same model produces correct normals:

![babylonjs_good](https://cloud.githubusercontent.com/assets/1235080/26522778/2976e5c8-42d6-11e7-9adf-53b389d19f5a.png)

As an experiment, I tried loading the so-called "DirectX normals" (as described in KhronosGroup/glTF#952), where the green channel intensity is inverted.  These normals do produce the correct output in master on this repo, but, I believe they do not meet the glTF 2.0 spec as it stands.

**Comment by bghgary** [comment]
@emackey Thanks for catching this! I was making an optimization that inadvertently broke the generated tangents such that the handedness is wrong. I didn't notice because most of the sample models have tangents specified. I will make a fix.

**Comment by emackey** [comment]
@bghgary Great!  Looking forward to merging a fix into my gltf-vscode extension.

On a related note, ThreeJS still isn't processing these normals correctly either.  That bug is reported separately in donmccurdy/three-gltf-viewer#10.

**Comment by bghgary** [comment]
This should be fixed with https://github.com/sbtron/BabylonJS-glTFLoader/commit/f8f5db031fae3649ac05967230c9897b3ecd1514

The PR for BabylonJS is here: https://github.com/BabylonJS/Babylon.js/pull/2222

**Comment by emackey** [comment]
Well... I merged this into my fork, but it doesn't look like anything changed.  Maybe the fix didn't get deployed to a release branch or something yet?

https://emackey.github.io/BabylonJS-glTFLoader/?model=NormalTangentTest

**Comment by bghgary** [comment]
Oops, sorry about that. I pushed the wrong version. Fixed now.

**Comment by emackey** [comment]
Awesome!  Fix confirmed.
