### ISSUE TITLE
Occlusion and Emissive textures both have incorrect error message

### ISSUE THREAD

**Issue by emackey** [sbtron/BabylonJS-glTFLoader#8]
The occlusion texture and the emissive texture both say `Failed to load normal texture` when they fail.

[babylon.glTFFileLoader.js#L819-L833](https://github.com/sbtron/BabylonJS-glTFLoader/blob/8c3902795da9c0c646834c2c87794c521d8a64f8/scripts/babylon.glTFFileLoader.js#L819-L833)

**Comment by bghgary** [comment]
Thanks for the report! I have fixed this locally and will update when I get a chance.

**Comment by bghgary** [comment]
This was fixed a while back.
